Repository GarimaSingh0109/WasteManagment, pull requests merged in 2024-10, with the labels that each got.

#161 Updated Ui
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#74 rate us
  index.html
  script.js
  styles.css
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#103 I have made some changes to both the HTML file and added an image to the assets folder and I also made changes in the CSS file.
  assets/header.jpg
  ecotips.html
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#107 #101 Added the Update index.html
  index.html
Labels: gssoc-ext, level1

#244 Issue: Content Overflow in Responsive Layout #233
  styles.css
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#336 Responsiveness and darkmode is added
  .vscode/settings.json
  index.html
  script.js
  styles.css
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#370 issue fixed mini chatbot
  bot.jpg
  chatbot.gif
  chatbot.html
  index.html
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#375 [Feature]Revamp Homepage CSS & Add Relevant Images for Enhanced UI #352
  assets/6824802.jpg
  assets/6881999.jpg
  assets/arrangement-cooked-fish-leftovers-recycle-symbol.jpg
  assets/front-view-recycling-basket-grass-with-trash.jpg
  assets/rb_2148298503.png
  assets/rb_8795.png
  index.html
  register.html
  script.js
  styles.css
Labels: gssoc-ext, hacktoberfest, level3, hacktoberfest-accepted

#373 Redesign of carbon footprint page
  .vscode/settings.json
  Carbo-footprint.css
  carbon-footprint.html
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#108 #94 changes the colur of a bold text or Updated styles.css
  styles.css
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#379 [Feature] No CSS Applied to ecotipes.html #354
  .vscode/settings.json
  README.md
  ecotips.html
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#382 [BUG] [UI Improvement] Update Outdated Navbar Buttons #376
  README.md
  styles.css
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#260 Implemented seamless realtime waste monitoring feature
  assets/landfill.avif
  assets/organic.jpg
  assets/papercup.avif
  assets/pbottle.avif
  assets/peel.jpg
  assets/rbin.jpg
  ecotips.html
  index.html
  realtime-monitoring.css
  realtime-monitoring.html
  script.js
  styles.css
Labels: gssoc-ext, hacktoberfest, level3, hacktoberfest-accepted

#398 Updated Mission and Signup Section Interface
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest, level2, hacktoberfest-accepted

#403 Add Github workflows For Task automation
  .github/workflows/auto_comment_on_issue.yml
  .github/workflows/auto_comment_pr_merge.yml
  .github/workflows/auto_comment_pr_raise.yml
  .github/workflows/auto_label_pr.yml
  .github/workflows/auto_lable_issue.yml
  .github/workflows/close_issue_on_pr_merge.yml
  .github/workflows/comment_iss-close.yml
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#402 Add chatbot + Multilanguage support to the website
  index.html
  requirements.txt
Labels: gssoc-ext, hacktoberfest, level3, hacktoberfest-accepted
